"""
Run one LinkedIn command with encrypted cache restoration and temporary plaintext browser state.
"""

from __future__ import annotations

import argparse
import hashlib
import logging
import os
import platform
import shutil
import signal
import subprocess
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING

from resumeme.config import load_config
from resumeme.exceptions import SessionCacheError
from resumeme.linkedin.retrying import is_retryable_linkedin_exit_status, retry
from resumeme.linkedin.session.cache import CacheKeys, archive_profile, open_archive, restore_profile, seal_archive
from resumeme.telemetry import logging_context

if TYPE_CHECKING:
    from types import FrameType

    from resumeme.config import Config

_SECRETS = ("RESUMEME_CACHE_PRIVATE_KEY", "RESUMEME_CACHE_PUBLIC_KEY", "RESUMEME_CACHE_KEY_PASSWORD")
_LOGGER = logging.getLogger("resumeme.ci.linkedin_session")
# GitHub has no native job retry policy, so retry every LinkedIn command in a clean session at most three times.
_MAX_LINKEDIN_ATTEMPTS = 4
_LINKEDIN_COMMANDS = frozenset({"capture", "capture-plan", "capture-shard", "publish-ownership", "publish-resume", "publish-skills"})


def cache_keys() -> CacheKeys | None:
    """
    Enable reuse only with a complete dedicated encryption identity.

    Returns:
        CacheKeys | None: Validated keys, or None when caching is not configured.

    Raises:
        SessionCacheError: One key is missing or the configured PEM pair is invalid.
    """
    private, public, password = (os.environ.get(name, "").encode() for name in _SECRETS)

    if not private and not public and not password:
        return None

    if not private or not public:
        raise SessionCacheError("Set both RESUMEME_CACHE_PRIVATE_KEY and RESUMEME_CACHE_PUBLIC_KEY to enable encrypted caching.")

    return CacheKeys.from_pem(private, public, password or None)


def output(name: str, value: str) -> None:
    """
    Export non-secret scalar metadata when running inside Actions.

    Args:
        name (str): Fixed output name.
        value (str): Single-line value generated by this script.

    Returns:
        None: GitHub receives the output when its output file is configured.

    Raises:
        SessionCacheError: A value contains a newline that cannot safely be exported.
    """
    if "\n" in value or "\r" in value:
        raise SessionCacheError("Session-cache metadata must be a single line.")

    if destination := os.environ.get("GITHUB_OUTPUT"):
        with Path(destination).open("a") as stream:
            stream.write(f"{name}={value}\n")


def write_encrypted(path: Path, data: bytes) -> None:
    """
    Atomically replace an encrypted envelope without leaving a partial cache after interruption.

    Args:
        path (Path): Destination containing ciphertext only.
        data (bytes): Authenticated encrypted archive.

    Returns:
        None: The complete envelope is installed with private permissions.
    """
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)

    with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as stream:
        temporary = Path(stream.name)

        try:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
            temporary.replace(path)
        finally:
            temporary.unlink(missing_ok=True)


def clean() -> None:
    """
    Remove only the temporary session directory exported by this job after a cancelled command.

    Returns:
        None: No plaintext browser state remains at the job's recorded temporary path.

    Raises:
        SessionCacheError: The exported path is outside the expected temporary-directory namespace.
    """
    value = os.environ.get("RESUMEME_SESSION_WORKDIR")

    if not value:
        return

    path = Path(value).resolve()
    parent = Path(os.environ.get("RUNNER_TEMP", tempfile.gettempdir())).resolve()

    if path.parent != parent or not path.name.startswith("resumeme-browser-"):
        raise SessionCacheError("Refusing to clean an unexpected session directory.")

    if path.exists():
        shutil.rmtree(path)


def _execute_command(
    command: list[str],
    config: Config,
    keys: CacheKeys | None,
    context: bytes,
    archive: Path,
    persistent: Path | None,
    *,
    retry_linkedin: bool,
) -> int:
    """
    Run one isolated browser attempt and persist state only after command success.

    Args:
        command (list[str]): Validated resumeme command and arguments.
        config (Config): Browser profile settings used to locate encrypted state.
        keys (CacheKeys | None): Encryption identity, absent when session caching is disabled.
        context (bytes): Repository and owner binding authenticated with the archive.
        archive (Path): Checkout-local encrypted session archive.
        persistent (Path | None): Optional runner-local destination for encrypted bytes.
        retry_linkedin (bool): Whether the child may emit the reserved retry exit status.

    Returns:
        int: Successful status, permanent failure status, or a classified retry status.
    """
    with tempfile.TemporaryDirectory(prefix="resumeme-browser-", dir=os.environ.get("RUNNER_TEMP")) as temporary:
        state = Path(temporary)

        if destination := os.environ.get("GITHUB_ENV"):
            with Path(destination).open("a") as stream:
                stream.write(f"RESUMEME_SESSION_WORKDIR={state}\n")

        source = persistent if persistent is not None and persistent.is_file() else archive

        if keys and source.is_file():
            restore_profile(open_archive(source.read_bytes(), keys, context), state / config.capture.browser)
            print("Restored authenticated encrypted browser cache.", flush=True)

        # Signing and LinkedIn credentials never enter the child; retry classification is an explicit non-secret flag.
        environment = {name: value for name, value in os.environ.items() if name not in _SECRETS}
        environment["RESUMEME_BROWSER_STATE_DIR"] = str(state)

        if retry_linkedin:
            environment["RESUMEME_CI_RETRY_LINKEDIN"] = "1"

        result = subprocess.run(command, env=environment, check=False)

        # A failed or interrupted interaction cannot replace the last accepted encrypted login state.
        if result.returncode == 0 and keys and os.environ.get("RESUMEME_SESSION_CACHE_READ_ONLY") != "true":
            data = seal_archive(archive_profile(state / config.capture.browser), keys, context)
            write_encrypted(archive, data)

            if persistent is not None:
                write_encrypted(persistent, data)

            output("cache-ready", "true")

        if retry_linkedin and is_retryable_linkedin_exit_status(result.returncode):
            raise subprocess.CalledProcessError(result.returncode, command)

        if result.returncode < 0:
            return 128 + -result.returncode

        return result.returncode


def _retryable_linkedin_failure(error: Exception) -> bool:
    """
    Restrict whole-command retries to explicitly classified LinkedIn failures.

    Args:
        error (Exception): Failure propagated from one browser command attempt.

    Returns:
        bool: Whether the error carries a retryable LinkedIn process status.
    """
    return isinstance(error, subprocess.CalledProcessError) and is_retryable_linkedin_exit_status(error.returncode)


def _should_retry_linkedin(error: Exception, command: str) -> bool:
    """
    Log the command boundary when a failed LinkedIn subprocess will receive another attempt.

    Args:
        error (Exception): Failure propagated from one browser command attempt.
        command (str): Validated LinkedIn command name.

    Returns:
        bool: Whether the failure is classified for a full command retry.
    """
    retryable = _retryable_linkedin_failure(error)

    if retryable:
        _LOGGER.warning(
            "Retrying LinkedIn command in a fresh browser session",
            extra={"linkedin.command": command, "retry.limit": _MAX_LINKEDIN_ATTEMPTS},
        )

    return retryable


def run() -> int:
    """
    Prepare cache metadata, execute a browser command, or clean up an interrupted job.

    Returns:
        int: Command exit status; cache or configuration failures raise for the caller to report.

    Raises:
        SessionCacheError: Configuration, encryption, archive ownership, or persistent cache paths are invalid.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("operation", choices=["prepare", "run", "clean"])
    parser.add_argument(
        "--command",
        choices=["capture", "capture-plan", "capture-shard", "publish-ownership", "publish-resume", "publish-skills"],
        default="capture",
    )
    parser.add_argument("--interactive", action="store_true", help="Bootstrap the encrypted session in a visible local browser")
    args = parser.parse_args()

    if args.operation == "clean":
        clean()
        return 0

    root = Path.cwd().resolve()
    config = load_config(root / "resumeme.config.yaml")
    keys = cache_keys()
    context = "\n".join(
        [
            os.environ.get("GITHUB_REPOSITORY", ""),
            config.linkedin.username.casefold(),
            config.capture.browser,
            platform.system(),
            platform.machine(),
        ]
    ).encode()
    identity = hashlib.sha256(context).hexdigest()
    # The readable browser component keeps Firefox and Chrome cache entries separate before any identity hash is inspected.
    prefix = f"resumeme-session-v2-{config.capture.browser}-{identity}-{keys.fingerprint() if keys else 'disabled'}"
    archive = root / ".cache/encrypted-session" / f"{prefix}.bin"
    persistent: Path | None = None

    if location := os.environ.get("RESUMEME_SESSION_CACHE_DIR", "").strip():
        directory = Path(location).expanduser()

        if not keys or not directory.is_absolute() or directory.resolve().is_relative_to(root):
            raise SessionCacheError(
                "Persistent session caching requires encryption keys and an absolute cache directory outside the checkout."
            )

        persistent = directory.resolve() / f"{prefix}.bin"

    if args.operation == "prepare":
        output("enabled", str(keys is not None).lower())
        output("cache-path", str(archive))
        output("cache-prefix", prefix + "-")
        output(
            "cache-key",
            prefix + "-" + "-".join(os.environ.get(name, "local") for name in ("GITHUB_RUN_ID", "GITHUB_RUN_ATTEMPT", "GITHUB_JOB")),
        )
        return 0

    if args.command in {"capture-plan", "capture-shard"} and keys is None:
        raise SessionCacheError("Six-way capture requires the dedicated encrypted LinkedIn session cache keys.")

    commands = {
        "capture": [],
        "capture-plan": ["--output", os.environ.get("SESSION_PLAN_PATH", ".cache/capture/plan.json")],
        "publish-ownership": ["--public-key", ".cache/publication/cosign.pub"],
        "publish-resume": ["--pdf", ".cache/publication/resume.pdf"],
        "publish-skills": ["--tag", os.environ.get("GITHUB_REF_NAME", ""), "--suggestions", ".cache/codex/skills/skills.json"],
    }

    if args.command == "capture-shard":
        try:
            shard_index = int(os.environ["SESSION_SHARD_INDEX"])
            shard_count = int(os.environ.get("SESSION_SHARD_COUNT", "6"))
        except (KeyError, ValueError) as error:
            raise SessionCacheError("capture-shard requires numeric SESSION_SHARD_INDEX and SESSION_SHARD_COUNT inputs.") from error

        if not 1 <= shard_index <= shard_count or not 1 <= shard_count <= 12:
            raise SessionCacheError("capture-shard requires a one-based shard index and a shard count between one and twelve.")

        shard_output = os.environ.get("SESSION_SHARD_OUTPUT", "").strip() or f".cache/capture/shards/shard-{shard_index}.json"
        commands[args.command] = [
            "--index",
            str(shard_index),
            "--count",
            str(shard_count),
            "--plan",
            os.environ.get("SESSION_PLAN_PATH", ".cache/capture/plan.json"),
            "--output",
            shard_output,
        ]

    command = ["resumeme", args.command, *([] if args.interactive else ["--headless"]), *commands[args.command]]
    retry_linkedin = args.command in _LINKEDIN_COMMANDS

    # Every retry starts a clean browser session; writes reconcile server state before they are repeated.
    with logging_context(os.environ.get("RESUMEME_LOG_LEVEL") or config.logging.level):
        try:
            return retry(
                lambda: _execute_command(
                    command,
                    config,
                    keys,
                    context,
                    archive,
                    persistent,
                    retry_linkedin=retry_linkedin,
                ),
                attempts=_MAX_LINKEDIN_ATTEMPTS if retry_linkedin else 1,
                backoff=config.capture.retry_backoff_seconds,
                max_backoff=config.capture.retry_max_backoff_seconds,
                exceptions=(subprocess.CalledProcessError,),
                should_retry=lambda error: _should_retry_linkedin(error, args.command),
            )
        except subprocess.CalledProcessError as error:
            _LOGGER.error(
                "LinkedIn command failed after bounded whole-session retries",
                extra={
                    "error.type": type(error).__name__,
                    "process.exit_code": error.returncode,
                    "retry.limit": _MAX_LINKEDIN_ATTEMPTS,
                },
            )
            return 128 + -error.returncode if error.returncode < 0 else error.returncode


def interrupt(signum: int, frame: FrameType | None) -> None:
    """
    Unwind temporary storage when the runner terminates the active step.

    Args:
        signum (int): Termination signal.
        frame (FrameType | None): Interrupted frame, unused.

    Returns:
        None: This handler exits through the caller's cleanup contexts.

    Raises:
        KeyboardInterrupt: Termination was requested.
    """
    raise KeyboardInterrupt


if __name__ == "__main__":
    signal.signal(signal.SIGTERM, interrupt)

    try:
        raise SystemExit(run())
    except (SessionCacheError, OSError) as error:
        print(f"Encrypted session cache failed: {error}", flush=True)
        raise SystemExit(2) from error
    except KeyboardInterrupt:
        raise SystemExit(130) from None
